# Configures Elasticsearch to log only to the console.
rootLogger: INFO, console

appender:
  console:
    type: console
    layout:
      type: consolePattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"
